name: Format
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Install Astro Plugin
        uses: actions/setup-node@v5
        with:
          node-version: 'latest'

      - run: npm install -D prettier-plugin-astro

      - name: Prettier Action
        uses: creyD/prettier_action@v4.6
        with:
          allow_other_plugins: true
          prettier_options: "--config .prettierrc --write {**/*,*}.{js,html,json,md,yml,css,astro}"
          file_pattern: "."
          prettier_plugins: "prettier-plugin-astro"
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
